var product =[{
		"id":0,
		"src":"img/pic18.jpg",
		"text":"(官方正品，专营店直销)欧舒丹美肌无暇保湿霜50ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":340,
		"checked":false
	},{
		"id":1,
		"src":"img/pic_1.jpg",
		"text":"美肌无暇保湿霜50ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":340,
		"checked":false
	},{
		"id":2,
		"src":"img/pic_2.jpg",
		"text":"美肌保湿喷雾100ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":160,
		"checked":false
	},{
		"id":3,
		"src":"img/pic_3.jpg",
		"text":"美肌无暇精华30ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":400,
		"checked":false
	},{
		"id":4,
		"src":"img/pic_4.jpg",
		"text":"美肌无暇修颜乳30ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":340,
		"checked":false
	},{
		"id":5,
		"src":"img/pic_5.jpg",
		"text":"芍药淡香水75ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":430,
		"checked":false
	},{
		"id":6,
		"src":"img/pic_6.jpg",
		"text":"芍药润肤霜200ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":380,
		"checked":false
	},{
		"id":7,
		"src":"img/pic_7.jpg",
		"text":"芍药润唇膏 玫瑰色4g",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":160,
		"checked":false
	},{
		"id":8,
		"src":"img/pic_8.jpg",
		"text":"芍药花香润手霜75ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":170,
		"checked":false
	},{
		"id":9,
		"src":"img/pic_9.jpg",
		"text":"芍药沐浴啫喱250ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":180,
		"checked":false
	},{
		"id":10,
		"src":"img/pic_10.jpg",
		"text":"芍药润肤露250ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":260,
		"checked":false
	},{
		"id":11,
		"src":"img/pic_11.jpg",
		"text":"芍药滚珠香水10ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":220,
		"checked":false
	},{
		"id":12,
		"src":"img/pic_12.jpg",
		"text":"芍药花香皂75g",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":"60",
		"checked":false
	},{
		"id":13,
		"src":"img/pic_13.jpg",
		"text":"焕亮防晒乳30ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":390,
		"checked":false
	},{
		"id":14,
		"src":"img/pic_14.jpg",
		"text":"蜡菊活颜BB霜40ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":380,
		"checked":false
	},{
		"id":15,
		"src":"img/pic_15.jpg",
		"text":"焕亮防晒乳30ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":380,
		"checked":false
	},{
		"id":16,
		"src":"img/pic_16.jpg",
		"text":"蜡菊活颜BB霜40ML",
		"count":1,
		"discount":"无",
		"cost":"",
		"price":390,
		"checked":false
	}
];